---

- name: Check CPU cores available
  fail:
    msg: This system does not meet the minimum amount of vCPU's
  failed_when: ansible_processor_vcpus < systemcheck_cpus

- name: Check Physical Memory available
  fail:
    msg: This system does not meet the minimum amount of  physical memory
  failed_when: ansible_memory_mb.real.total < systemcheck_physical_memory

#- name: Check Swap Memory
#  fail:
#    msg: This system does not meet the minimum amount of swap memory
#  failed_when: ansible_memory_mb.swap.total < systemcheck_swap_memory

- name: Check disk-size
  fail:
    msg: This system does not meet the minimum amount of  disk-space
  with_items: "{{ ansible_mounts }}"
  loop_control:
    label: "{{ item.device }}"
  failed_when: item.size_total < systemcheck_disk
  when: item.mount == "/"